#!/usr/bin/ruby
# -*- coding: UTF-8 -*-
require 'etc'
# User runnig this script, whose Thunderbird will be auto configured
user = Etc.getlogin
# This script only configures users authenticated against an external source, having "*" as password in /etc/passwd
pwd = Etc.getpwnam(user)
# thunderdir = ".thunderbird"
# While testing use a different value not to misconfigure your own thunderbird
thunderdir = ".hummingbird"

# Variables that define the email/calendar corporate service
mydomain = "@juntadeandalucia.es"
imapserver = "imap.juntadeandalucia.es"
smtpserver = "mail.juntadeandalucia.es"
imapport = 143
imapsockettype = 2
imapauthmethod = 3
smtpport = 465
smtptryssl = 3
smtpauthmethod = 3

# Presente version of GCA keeps auhtentication method in /etc/gca-sssd.control
# TODO check authentication method in a more standard and secure way
# TODO implement extraction of email and displayname from LDAP
if pwd.passwd == '*' and File.file?("/etc/gca-sssd.control") and File.readable?("/etc/gca-sssd.control") and IO.read("/etc/gca-sssd.control").include? '{"auth_type": "ad"}'
  result = `net ads search  '(sAMAccountName=#{user})' sAMAccountName mail displayName 2>/dev/null`
  # Name of the user to be displayed as account name
  displayname=""
  # Commplete email address of the user
  mail=""
  # Usernme to authenticate against the mail/calendar servers
  mailuser=""
  if result =~ /\AGot 1 replies/ and (result =~ /sAMAccountName: #{user}/ or result =~ /sAMAccountName: #{user.upcase}/)
    result.each_line {|line|
      var,value=line.split(":")
      if var == "displayName" 
        displayname = value.strip
      end
      if var == "mail"
        mail = value.strip
        mailuser = mail.gsub(mydomain,"")
      end
      }
      
    if displayname and mail and mail != mailuser 
      # TODO include lines to configure a remote CalDAV calendar server
      user_js = <<x
# Thunderbird User Preferences (generated by GECOS)

/* Do not edit this file.
*
* If you make changes to this file while the application is running,
* the changes will be overwritten when the application exits.
*
* To make a manual change to preferences, you can visit the URL about:config
*/

# Account
user_pref("mail.accountmanager.defaultaccount", "account1");
user_pref("mail.accountmanager.accounts", "account1");
user_pref("mail.account.account1.server", "server1");
user_pref("mail.account.account1.identities", "id1");
user_pref("mail.accountmanager.localfoldersserver", "server2");

# IMAP Server
user_pref("mail.server.server1.type", "imap");
user_pref("mail.server.server1.hostname", "#{imapserver}");      
user_pref("mail.server.server1.port", #{imapport});
user_pref("mail.server.server1.socketType", #{imapsockettype}); // STARTTLS
user_pref("mail.server.server1.userName", "#{mailuser}");               
user_pref("mail.server.server1.authMethod", #{imapauthmethod}); // normal password
user_pref("mail.server.server1.login_at_startup", true);

# SMTP Server
user_pref("mail.smtpservers", "smtp1");
user_pref("mail.smtpserver.smtp1.hostname","#{smtpserver}");
user_pref("mail.smtpserver.smtp1.port", #{smtpport});
user_pref("mail.smtpserver.smtp1.try_ssl", #{smtptryssl}); // SSL/TLS
user_pref("mail.smtpserver.smtp1.username", "#{mailuser}");
user_pref("mail.smtpserver.smtp1.authMethod", #{smtpauthmethod}3); // SSL/TLS

# Identity
user_pref("mail.identity.id1.fullName", "#{displayname}");
user_pref("mail.identity.id1.useremail", "#{mailuser}@juntadeandalucia.es");
user_pref("mail.identity.id1.valid", true);
user_pref("mail.identity.id1.smtpServer", "smtp1");
      
x
      profiles_ini = <<x
[General]
StartWithLastProfile=1

[Profile0]
Name=.thunderbird/
IsRelative=0
Path=/home/#{user}/.thunderbird

x
      if !(File.exist?("/home/#{user}/#{thunderdir}/user.js") and File.size?("/home/#{user}/#{thunderdir}/user.js") == user_js.size + 1)       
        if !File.directory?("/home/#{user}/#{thunderdir}")
          Dir.mkdir("/home/#{user}/#{thunderdir}")
        end
        IO.write("/home/#{user}/#{thunderdir}/user.js",user_js)
        IO.write("/home/#{user}/#{thunderdir}/profiles.ini",profiles_ini)
      else
        puts "Ya configurado \n"  
      end
    end  
  end
end
